services:
  titi:
    container_name: titi

    build:
      context: .
      dockerfile: Dockerfile

      args:
        DATABASE_URL: ${DATABASE_URL}

        NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}

        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}

        PI_API_URL: ${PI_API_URL}
        PI_API_KEY: ${PI_API_KEY}
        PI_HORIZON_URL: ${PI_HORIZON_URL}
        PI_NETWORK_PASSPHRASE: ${PI_NETWORK_PASSPHRASE}
        PI_WALLET_PRIVATE_SEED: ${PI_WALLET_PRIVATE_SEED}

    environment:
      NODE_ENV: production

      DATABASE_URL: ${DATABASE_URL}

      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL}

      NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}

      PI_API_URL: ${PI_API_URL}
      PI_API_KEY: ${PI_API_KEY}
      PI_HORIZON_URL: ${PI_HORIZON_URL}
      PI_NETWORK_PASSPHRASE: ${PI_NETWORK_PASSPHRASE}
      PI_WALLET_PRIVATE_SEED: ${PI_WALLET_PRIVATE_SEED}

    ports:
      - "3000:3000"

    restart: unless-stopped
